### ISSUE TITLE
Multi-scale Registration in Open3D even lower the performance

### ISSUE THREAD

**Issue by gitouni** [hanzheteng/color_icp#3]
Actually, the issue https://github.com/hanzheteng/color_icp/issues/2 also happens in the [script](https://github.com/hanzheteng/color_icp/blob/main/scripts/colored_icp.py). ICP performs better than colored_ICP in registration between [color_bin_00_easy.pcd](https://github.com/hanzheteng/color_icp/blob/main/data/cloud_bin_00_easy.pcd) and [color_bin_01.pcd](https://github.com/hanzheteng/color_icp/blob/main/data/cloud_bin_01.pcd). Your comment makes me convinced that there are some scenarios not proper for colored method, thanks.

Note: you can use the following json setting to view the Open3D's view (Ctrl + V on the view window). Manifest difference can be found on the boundary of the armchair.
```json
{
	"class_name" : "ViewTrajectory",
	"interval" : 29,
	"is_loop" : false,
	"trajectory" : 
	[
		{
			"boundingbox_max" : [ 3.43359375, 2.7008078098297119, 2.1282944679260254 ],
			"boundingbox_min" : [ -0.30465653538703918, 0.89872455596923828, 0.47970101237297058 ],
			"field_of_view" : 60.0,
			"front" : [ 0.72311997525859728, -0.12254874450305511, -0.67976415513230082 ],
			"lookat" : [ 1.5644686073064804, 1.7997661828994751, 1.303997740149498 ],
			"up" : [ -0.27748035007253208, -0.95277190584179838, -0.12341130727049508 ],
			"zoom" : 0.099999999999999617
		}
	],
	"version_major" : 1,
	"version_minor" : 0
}
```

What makes me confused is the problem disappered when I use your [color_icp.cpp](https://github.com/hanzheteng/color_icp/blob/main/src/color_icp.cpp) file to register. It seems to show the multi-scale scheme for Colored ICP even lower its performance.

**Comment by gitouni** [comment]
I supplement the pictures to visualizae the registration difference between your cpp and Open3D's implementation.
Open3D's
![image](https://user-images.githubusercontent.com/30369762/225800788-c32669b5-3cef-44f3-9502-ae8ad43286cc.png)
Your's (in Open3D viewer)
![image](https://user-images.githubusercontent.com/30369762/225800868-73eb1df5-a352-4c7d-93b5-87422d824185.png)
I believe your result is better. Certainlly, the Open3D's implementation uses multi-scale registration thus it is not equivalent to your implementation in this repo. I guess possbile reasons can be:

* voxel size: Open3D's official implementation uses multi-scale scheme, i.e., 0.05, 0.03 and 0.01. For yours, voxel is fixed to 0.01.
* max_corr distance: The radius is set for ICP correspondence search. For Open3D, it varies among different scales. For yours, it is fixed to 0.05.
* color search radius: The parameter is set for color gradient calculation. For Open3D, I don't know the default setting. For yours, it is set to 0.04.
* iterations: Yours is 50 while Open3D also varies among different scale levels.
* optimization method: Yours is Guassian-Newton. For Open3D, I also don't know.

I also try to set parameters (except the color search radius and optimization method) of Open3D to be same with yours. 
```py
def colored_icp_registration(source, target, voxel_size):
    print("Colored ICP registration")
    voxel_radius = [voxel_size]  # 0.01
    max_iter = [50]
    current_transformation = np.identity(4)
    for scale in range(len(voxel_radius)):
        max_it = max_iter[scale]
        radius = voxel_radius[scale]*5  # 0.05
        print("scale_level = {0}, voxel_size = {1}, max_iter = {2}".format(scale, radius, max_it))
        source_down = source.voxel_down_sample(radius)
        target_down = target.voxel_down_sample(radius)
        source_down.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=radius*2, max_nn=20))
        target_down.estimate_normals(o3d.geometry.KDTreeSearchParamHybrid(radius=radius*2, max_nn=20))
        result = o3d.pipelines.registration.registration_colored_icp(
            source_down, 
            target_down, 
            radius*2, 
            current_transformation,
            o3d.pipelines.registration.TransformationEstimationForColoredICP(),
            o3d.pipelines.registration.ICPConvergenceCriteria(relative_fitness=1e-6,
                                                              relative_rmse=1e-6,
                                                              max_iteration=max_it))
        current_transformation = result.transformation
        # draw_registration_result(source, target, current_transformation, color=True)

        print(result)
    print(current_transformation)
    tmp = np.loadtxt("./cpp_res.txt")
    draw_registration_result(source, target, current_transformation, color=True)  # Open3D
    draw_registration_result(source, target, tmp, color=True)  # cpp result
```
But it also doesn't work:
![image](https://user-images.githubusercontent.com/30369762/225803169-517e05ae-661c-4946-826e-31e39c2d4336.png)

Is there any magic?

**Comment by hanzheteng** [comment]
I found the magic there :) 

At the beginning, I fixed a few places that are different in the Python script you used and the C++ configuration of the ColorICP in this project, including the search radius for kdtree and normal estimation, and maximum correspondence distance threshold, etc. Even though you changed the multi-scale scheme to one iteration, these parameters are not set properly/exactly the same as in C++, leading to possible differences in results. Below is a simplified/fixed version of the Python script.

``` Python
def colored_icp_registration(source, target, voxel_size):
    print("Colored ICP registration")
    max_iter = 50
    search_radius = voxel_size * 5
    max_corres_dist = voxel_size * 5
    current_transformation = np.identity(4)
    source_down = source.voxel_down_sample(voxel_size)
    target_down = target.voxel_down_sample(voxel_size)
    print("Contained " + str(len(source_down.points)) + " points after downsampling")
    print("Contained " + str(len(target_down.points)) + " points after downsampling")
    source_down.estimate_normals(o3d.geometry.KDTreeSearchParamRadius(radius=search_radius))
    target_down.estimate_normals(o3d.geometry.KDTreeSearchParamRadius(radius=search_radius))
    result = o3d.pipelines.registration.registration_colored_icp(
        source_down, 
        target_down, 
        max_corres_dist, 
        current_transformation,
        o3d.pipelines.registration.TransformationEstimationForColoredICP(),
        o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=max_iter))
    current_transformation = result.transformation
    print(current_transformation)
    draw_registration_result(source, target, current_transformation, color=True)

if __name__ == "__main__":
    # parameters
    voxel_size = 0.01
    source = o3d.io.read_point_cloud("/tmp/source_test.pcd")
    target = o3d.io.read_point_cloud("/tmp/target_test.pcd")
    print("Loaded " + str(len(source.points)) + " points for source point cloud")
    print("Loaded " + str(len(target.points)) + " points for target point cloud")

    # colored ICP
    colored_icp_registration(source, target, voxel_size)
```

However, the result remains as what you reported in the screenshots. Then I looked into other differences, and finally identified the root of the cause that NaN RGB points are removed in my cpp implementation but not in the Open3D code. As you can see, there are no NaN points present in 3D space, but the number of points is reduced after removing NaN RGB points. 

```
Loaded 196133 source points
Loaded 136920 target points
Contained 196133 points after removing NaN points
Contained 183039 points after removing NaN RGB points
Contained 136920 points after removing NaN points
Contained 135529 points after removing NaN RGB points
Downsampled to 90850 points
Downsampled to 63160 points
```

In Open3D, they also offered the function to remove NaN points in 3D space (`remove_non_finite_points`), but I don't think they have a function to remove NaN points in color space.

Then I saved the point clouds after NaN RGB points were removed in C++ implementation, used these two clouds as input for the Python script, and obtained identical results. The results produced by the C++ implementation in this repo and that produced by the Python code from Open3D are supposed to be the same, as long as all the rest of the conditions are the same.

I am unable to upload them here directly (file type not supported by github), but you can try to save them as follows in C++, and verify if this is true on your end as well.
``` C++
  // pre-processing
  removeNaNPoints (source_cloud_);
  removeNaNPoints (target_cloud_);
  pcl::io::savePCDFile ("/tmp/source_test.pcd", *source_cloud_);
  pcl::io::savePCDFile ("/tmp/target_test.pcd", *target_cloud_);
  downSampleVoxelGrids (source_cloud_);
  downSampleVoxelGrids (target_cloud_);
```

**Comment by hanzheteng** [comment]
> Your comment makes me convinced that there are some scenarios not proper for colored method, thanks.

Lastly, a few more comments on the above statement: We can probably only say that this specific method of using color in ICP may not work in such scenarios, but I believe that there may exist some better methods to make use of color information and obtain a better result. It is the goal of the future research in our community, isn't it?  :)

**Comment by gitouni** [comment]
I truely appreciate your careful check. Your assumption is right: Open3D ignored the points with NaN color and that is why it does not work. 

I also tried to imlement this function to a pure python script. I found that Open3D will change every NaN color vector to [0,0,0]. Therefore, using `np.isnan()` and `np.isfinite` to judge NaN colors will still end up with failure. Instead, the operation `color==0` is enough. The python implementation is:

```py
import os
import copy
import numpy as np
import open3d as o3d


os.chdir(os.path.dirname(__file__))

def draw_registration_result(source, target, transformation, color=True):
    source_temp = copy.deepcopy(source)
    target_temp = copy.deepcopy(target)
    if not color:
        source_temp.paint_uniform_color([1, 1, 0])
        target_temp.paint_uniform_color([0, 1, 1])
    source_temp.transform(transformation)
    o3d.visualization.draw_geometries([source_temp, target_temp])
    
def remove_color_NaN(input_pt):
    rev_pt = o3d.geometry.PointCloud(input_pt)
    color = np.array(input_pt.colors)
    removed = np.arange(len(color))[color.sum(axis=1)==0]
    return rev_pt.select_by_index(removed, invert=True)
    
    
def colored_icp_registration(source, target, voxel_size):
    print("Colored ICP registration")
    max_iter = 50
    search_radius = voxel_size * 5
    max_corres_dist = voxel_size * 5
    current_transformation = np.identity(4)
    source_down = source.voxel_down_sample(voxel_size)
    target_down = target.voxel_down_sample(voxel_size)
    print("Contained " + str(len(source_down.points)) + " points after downsampling")
    print("Contained " + str(len(target_down.points)) + " points after downsampling")
    source_down.estimate_normals(o3d.geometry.KDTreeSearchParamRadius(radius=search_radius))
    target_down.estimate_normals(o3d.geometry.KDTreeSearchParamRadius(radius=search_radius))
    result = o3d.pipelines.registration.registration_colored_icp(
        source_down, 
        target_down, 
        max_corres_dist, 
        current_transformation,
        o3d.pipelines.registration.TransformationEstimationForColoredICP(),
        o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=max_iter))
    current_transformation = result.transformation
    print(current_transformation)
    draw_registration_result(source, target, current_transformation, color=True)

if __name__ == "__main__":
    # parameters
    voxel_size = 0.01
    source = o3d.io.read_point_cloud("../data/cloud_bin_00_easy.pcd",remove_nan_points=True, remove_infinite_points=True)
    target = o3d.io.read_point_cloud("../data/cloud_bin_01.pcd",remove_nan_points=True, remove_infinite_points=True)
    
    print("Loaded " + str(len(source.points)) + " points for source point cloud")
    print("Loaded " + str(len(target.points)) + " points for target point cloud")
    source = remove_color_NaN(source)
    target = remove_color_NaN(target)
    print("Reserved " + str(len(source.points)) + " points for source point cloud")
    print("Reserved " + str(len(target.points)) + " points for target point cloud")
    # colored ICP
    colored_icp_registration(source, target, voxel_size)
```
The output:
```
Loaded 196133 points for source point cloud
Loaded 136920 points for target point cloud
Reserved 183039 points for source point cloud
Reserved 135529 points for target point cloud
Colored ICP registration
Contained 90834 points after downsampling
Contained 63332 points after downsampling
[[ 0.99981252  0.00474084 -0.0187737   0.05301755]
 [-0.00480869  0.99998206 -0.00357051  0.09860709]
 [ 0.01875643  0.00366012  0.99981738 -0.07043772]
 [ 0.          0.          0.          1.        ]]
```
I'm not sure whether the operation will remove points that are truely colored black (0,0,0). However, the number of reserved points is the same with yours. This time, it returns the correct registration as I reported before. Thanks again for your reply. You can also add this modification to your repo.
