### ISSUE TITLE
the score of color_icp

### ISSUE THREAD

**Issue by nuo-1** [hanzheteng/color_icp#5]
Hello, I would like to ask how the score of this algorithm should be given, similar to the icp. getFitnessScore() in icp

**Comment by hanzheteng** [comment]
This is an open problem. You can still use the score similar to `getFitnessScore()`, which measures the average errors in correspondences in 3D space. Alternatively, you can consider color components and compute a weighted geometry+color score.

**Comment by nuo-1** [comment]
Okay, thanks. I will refer to your suggestion and give it a try.

**Comment by nuo-1** [comment]
> This is an open problem. You can still use the score similar to `getFitnessScore()`, which measures the average errors in correspondences in 3D space. Alternatively, you can consider color components and compute a weighted geometry+color score.

Okay, thanks. I will refer to your suggestion and give it a try.
