### ISSUE TITLE
 The accuracy of the Redwood Indoor Dataset's groundtruth

### ISSUE THREAD

**Issue by sysu17363087** [hanzheteng/color_icp#6]
Hello,

Firstly, I would like to express my gratitude for your work. I am currently using the Redwood Indoor Dataset to train and test the D3Feat pointcloud registration method. However, as I was making groundtruth matching point pairs for training, I noticed that the groundtruth camera pose may not be accurate.

Upon visualizing the reconstruction point cloud and the point cloud generated from RGBD fragments with the provided pose, I noticed a distinct interval between the two point clouds. I am unsure whether this error is caused by the depth sensor or reconstruction method. Additionally, the error is not consistent across all fragments.

I would greatly appreciate any advice or insight you may have on this problem. Thank you for your time and assistance.

![2023-04-21 20-37-02 的屏幕截图](https://user-images.githubusercontent.com/56914037/233767732-e446dc3c-76bf-4db7-9ac9-3c8dbc7d3836.png)

![2023-04-21 20-27-58 的屏幕截图](https://user-images.githubusercontent.com/56914037/233767743-12e62f99-3a0c-4b62-8fee-11ed7a38a4be.png)

**Comment by hanzheteng** [comment]
Which dataset are you using exactly? I used to have issues with the ground truth for this [RGB-D Redwood dataset](http://redwood-data.org/indoor_lidar_rgbd/), but this [indoor reconstruction dataset](http://redwood-data.org/indoor/) is ok, since the ground truth is generated in simulation.

**Comment by sysu17363087** [comment]
> 

I'm using the [RGB-D Redwood dataset](http://redwood-data.org/indoor_lidar_rgbd/),for it contains pointclouds from two modalities sensors in real-world indoor environment. I am considering whether I should use ICP to refine the groundtruth values.

**Comment by hanzheteng** [comment]
For this dataset, it indeed has issues with the ground truth. I guess the "ground truth" poses provided in this dataset may be estimated by some online camera calibration algorithms (e.g., Simultaneous Localization and Calibration in authors' another work). 

You may try to improve the ground truth by ICP and manual inspection, but this can involve a large amount of time and efforts, and for some sequences the ICP algorithm may not converge if your initial guess is not good. Overall if you feel like this is the last resort, you may try.

Alternatively, there are some other datasets available. For example, look at the RGB-D Reconstruction Datasets listed under the 3DMatch project page: https://3dmatch.cs.princeton.edu/ But still, this one does not have the absolute ground truth. You may try to play with it and see if the generation of ground truth is easier for any one of them.

You may notice that there is also a section called Geometric Registration Benchmark, but this benchmark does not contain color modality. In their [Github page](https://github.com/andyzeng/3dmatch-toolbox#geometric-registration-benchmark), they provide a way to generate your own dataset for geometric registration benchmarking purposes. If you look into the source code, you will find that they only copied the geometric component of the original data to generate this benchmark. It is possible to change it a bit to copy color modality too. If you fix this script, you can get a bunch of datasets with color modality and ground truth, according to my current understanding.  

I hope the ideas above are useful for you. The last idea (fix their scripts to get a new dataset with color modality) is something I would like to try back to last year when I had issues with the ground truth of the Redwood dataset, but I did not eventually find the time to do it. If you end up doing it, please kindly let me know and share your progress.

**Comment by sysu17363087** [comment]
> 

Thank you for your reply, it's very helpful to me. I will try it later.
